### ISSUE TITLE
Middleware problen in deeplink

### ISSUE THREAD

**Issue by felimoles** [xcesaralejandro/lti1p3#8]
please change in the file routes/web.php the middleware for deeplinking to LtiInstanceResolver 

thanks you soo much 👍🏽

**Comment by xcesaralejandro** [comment]
Thanks @felimoles, it was fixed [here](https://github.com/xcesaralejandro/lti1p3/commit/08c6c86fa538c8919db090ddfb7e36f7cb3edc22). And tagged as [7.0.2](https://github.com/xcesaralejandro/lti1p3/releases/tag/7.0.2)
